language: node_js
node_js:
  - "0.8"
  - "0.9"
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.3"
sudo: false
before_install: "npm install -g readfileline;npm install -g workqueue"