environment:
  matrix:
    - nodejs_version: "0.8"
    - nodejs_version: "0.9"
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
    - nodejs_version: "1.8"
    - nodejs_version: "2.0"
    - nodejs_version: "2.3"
build: off
test_script:
  - node --version
  - npm --version
  - npm test
version: "{build}"